# Generated by Django 5.1 on 2024-08-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0004_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='empTask',
            fields=[
                ('employee_name', models.CharField(max_length=255)),
                ('emloyee_ID', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('mob_no', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('task_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('task_status', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
