# Generated by Django 5.1 on 2024-08-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0005_emptask_delete_invoice_delete_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emptask',
            old_name='emloyee_ID',
            new_name='employee_ID',
        ),
    ]
