# Generated by Django 5.1 on 2024-08-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0007_alter_emptask_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('ID', models.BigIntegerField(default=True, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('employee_role', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('attendance_status', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
            ],
        ),
    ]
