# Generated by Django 5.1 on 2024-08-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0009_atten'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkManualAttendance',
            fields=[
                ('employee_name', models.CharField(max_length=255)),
                ('ID', models.BigIntegerField(default=True, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('attendance_status', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
