# Generated by Django 5.1 on 2024-08-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0010_markmanualattendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atten',
            old_name='mobile_number',
            new_name='mobile_no',
        ),
    ]
