# Generated by Django 5.1 on 2024-08-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0011_rename_mobile_number_atten_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveAttendance',
            fields=[
                ('ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('from_date', models.DateField()),
                ('till_date', models.DateField()),
                ('total_leave', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
