# Generated by Django 5.1 on 2024-08-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0012_leaveattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitShop',
            fields=[
                ('ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('shop_name', models.CharField(max_length=255)),
                ('shop_address', models.TextField()),
                ('visiting_datetime', models.DateTimeField()),
                ('reason_for_visit', models.TextField()),
                ('image', models.ImageField(upload_to='visit_images/')),
            ],
        ),
    ]
