# Generated by Django 5.1 on 2024-08-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0014_orderinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('expense_type', models.CharField(max_length=255)),
                ('expense_description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('upload_bill', models.FileField(upload_to='bills/')),
            ],
        ),
    ]
